spring:
  application:
    name: dunning-service

  datasource:
    url: jdbc:postgresql://localhost:5437/dunning_db
    username: your_postgres_username
    password: your_postgres_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: dunning-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3

  quartz:
    job-store-type: memory
    properties:
      org:
        quartz:
          scheduler:
            instanceName: DunningScheduler
          threadPool:
            threadCount: 3

server:
  port: 8085

# URL interne de payment-service
payment-service:
  url: http://localhost:8084