name: saas-billing-platform
services:
  api-gateway:
    build:
      context: D:\Documents\Stages\Billing Saas App\saas-billing-platform\microservices\api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    depends_on:
      auth-service:
        condition: service_started
        required: true
      billing-service:
        condition: service_started
        required: true
      payment-service:
        condition: service_started
        required: true
      subscription-service:
        condition: service_started
        required: true
    environment:
      JWT_EXPIRATION: "3600000"
      JWT_REFRESH_EXPIRATION: "604800000"
      JWT_SECRET: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      SPRING_CLOUD_GATEWAY_ROUTES_0_URI: http://auth-service:8081
      SPRING_CLOUD_GATEWAY_ROUTES_1_URI: http://subscription-service:8082
      SPRING_CLOUD_GATEWAY_ROUTES_2_URI: http://billing-service:8083
      SPRING_CLOUD_GATEWAY_ROUTES_3_URI: http://payment-service:8084
    networks:
      billing-network: null
    ports:
      - mode: ingress
        target: 8080
        published: "8080"
        protocol: tcp
    restart: on-failure
  auth-service:
    build:
      context: D:\Documents\Stages\Billing Saas App\saas-billing-platform\microservices\auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    depends_on:
      kafka:
        condition: service_healthy
        required: true
      postgres-auth:
        condition: service_healthy
        required: true
      redis:
        condition: service_healthy
        required: true
    environment:
      JWT_EXPIRATION: "3600000"
      JWT_REFRESH_EXPIRATION: "604800000"
      JWT_SECRET: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: "6379"
      SPRING_DATASOURCE_PASSWORD: secret
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-auth:5432/auth_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "false"
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    networks:
      billing-network: null
    ports:
      - mode: ingress
        target: 8081
        published: "8081"
        protocol: tcp
    restart: on-failure
  billing-service:
    build:
      context: D:\Documents\Stages\Billing Saas App\saas-billing-platform\microservices\billing-service
      dockerfile: Dockerfile
    container_name: billing-service
    depends_on:
      kafka:
        condition: service_healthy
        required: true
      postgres-billing:
        condition: service_healthy
        required: true
    environment:
      JWT_SECRET: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      SPRING_DATASOURCE_PASSWORD: secret
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-billing:5432/billing_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "false"
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    networks:
      billing-network: null
    ports:
      - mode: ingress
        target: 8083
        published: "8083"
        protocol: tcp
    restart: on-failure
  client:
    build:
      context: D:\Documents\Stages\Billing Saas App\saas-billing-platform\microservices\client
      dockerfile: Dockerfile
    container_name: client
    depends_on:
      api-gateway:
        condition: service_started
        required: true
    networks:
      billing-network: null
    ports:
      - mode: ingress
        target: 80
        published: "3000"
        protocol: tcp
    restart: on-failure
  dunning-service:
    build:
      context: D:\Documents\Stages\Billing Saas App\saas-billing-platform\microservices\dunning-service
      dockerfile: Dockerfile
    container_name: dunning-service
    depends_on:
      kafka:
        condition: service_healthy
        required: true
      payment-service:
        condition: service_started
        required: true
      postgres-dunning:
        condition: service_healthy
        required: true
    environment:
      PAYMENT_SERVICE_URL: http://payment-service:8084
      SPRING_DATASOURCE_PASSWORD: secret
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-dunning:5432/dunning_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "false"
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    networks:
      billing-network: null
    ports:
      - mode: ingress
        target: 8085
        published: "8085"
        protocol: tcp
    restart: on-failure
  kafka:
    container_name: kafka
    environment:
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
      KAFKA_ADVERTISED_LISTENERS: |
        PLAINTEXT://localhost:9092, PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: |
        PLAINTEXT:PLAINTEXT, PLAINTEXT_INTERNAL:PLAINTEXT, CONTROLLER:PLAINTEXT
      KAFKA_LISTENERS: |
        PLAINTEXT://0.0.0.0:9092, PLAINTEXT_INTERNAL://0.0.0.0:29092, CONTROLLER://0.0.0.0:9093
      KAFKA_NODE_ID: "1"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_PROCESS_ROLES: broker,controller
    healthcheck:
      test:
        - CMD-SHELL
        - kafka-broker-api-versions --bootstrap-server localhost:9092
      timeout: 10s
      interval: 15s
      retries: 10
    image: confluentinc/cp-kafka:7.6.0
    networks:
      billing-network: null
    ports:
      - mode: ingress
        target: 9092
        published: "9092"
        protocol: tcp
      - mode: ingress
        target: 29092
        published: "29092"
        protocol: tcp
  mailhog:
    container_name: mailhog
    image: mailhog/mailhog
    networks:
      billing-network: null
    ports:
      - mode: ingress
        target: 1025
        published: "1025"
        protocol: tcp
      - mode: ingress
        target: 8025
        published: "8025"
        protocol: tcp
  notification-service:
    build:
      context: D:\Documents\Stages\Billing Saas App\saas-billing-platform\microservices\notification-service
      dockerfile: Dockerfile
    container_name: notification-service
    depends_on:
      kafka:
        condition: service_healthy
        required: true
      mailhog:
        condition: service_started
        required: true
    environment:
      APP_MAIL_FROM: noreply@billflow.com
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      SPRING_MAIL_HOST: mailhog
      SPRING_MAIL_PORT: "1025"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "false"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "false"
    networks:
      billing-network: null
    ports:
      - mode: ingress
        target: 8086
        published: "8086"
        protocol: tcp
    restart: on-failure
  payment-service:
    build:
      context: D:\Documents\Stages\Billing Saas App\saas-billing-platform\microservices\payment-service
      dockerfile: Dockerfile
    container_name: payment-service
    depends_on:
      kafka:
        condition: service_healthy
        required: true
      postgres-payment:
        condition: service_healthy
        required: true
    environment:
      JWT_SECRET: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      SPRING_DATASOURCE_PASSWORD: secret
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-payment:5432/payment_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "false"
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      STRIPE_API_KEY: sk_test_YOUR_STRIPE_TEST_KEY
      STRIPE_WEBHOOK_SECRET: whsec_YOUR_WEBHOOK_SECRET
    networks:
      billing-network: null
    ports:
      - mode: ingress
        target: 8084
        published: "8084"
        protocol: tcp
    restart: on-failure
  postgres-auth:
    container_name: postgres-auth
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: admin
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U admin -d auth_db
      timeout: 5s
      interval: 10s
      retries: 5
    image: postgres:15-alpine
    networks:
      billing-network: null
    ports:
      - mode: ingress
        target: 5432
        published: "5433"
        protocol: tcp
    volumes:
      - type: volume
        source: postgres_auth_data
        target: /var/lib/postgresql/data
        volume: {}
  postgres-billing:
    container_name: postgres-billing
    environment:
      POSTGRES_DB: billing_db
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: admin
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U admin -d billing_db
      timeout: 5s
      interval: 10s
      retries: 5
    image: postgres:15-alpine
    networks:
      billing-network: null
    ports:
      - mode: ingress
        target: 5432
        published: "5435"
        protocol: tcp
    volumes:
      - type: volume
        source: postgres_billing_data
        target: /var/lib/postgresql/data
        volume: {}
  postgres-dunning:
    container_name: postgres-dunning
    environment:
      POSTGRES_DB: dunning_db
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: admin
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U admin -d dunning_db
      timeout: 5s
      interval: 10s
      retries: 5
    image: postgres:15-alpine
    networks:
      billing-network: null
    ports:
      - mode: ingress
        target: 5432
        published: "5437"
        protocol: tcp
    volumes:
      - type: volume
        source: postgres_dunning_data
        target: /var/lib/postgresql/data
        volume: {}
  postgres-notification:
    container_name: postgres-notification
    environment:
      POSTGRES_DB: notification_db
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: admin
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U admin -d notification_db
      timeout: 5s
      interval: 10s
      retries: 5
    image: postgres:15-alpine
    networks:
      billing-network: null
    ports:
      - mode: ingress
        target: 5432
        published: "5438"
        protocol: tcp
    volumes:
      - type: volume
        source: postgres_notification_data
        target: /var/lib/postgresql/data
        volume: {}
  postgres-payment:
    container_name: postgres-payment
    environment:
      POSTGRES_DB: payment_db
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: admin
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U admin -d payment_db
      timeout: 5s
      interval: 10s
      retries: 5
    image: postgres:15-alpine
    networks:
      billing-network: null
    ports:
      - mode: ingress
        target: 5432
        published: "5436"
        protocol: tcp
    volumes:
      - type: volume
        source: postgres_payment_data
        target: /var/lib/postgresql/data
        volume: {}
  postgres-subscription:
    container_name: postgres-subscription
    environment:
      POSTGRES_DB: subscription_db
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: admin
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U admin -d subscription_db
      timeout: 5s
      interval: 10s
      retries: 5
    image: postgres:15-alpine
    networks:
      billing-network: null
    ports:
      - mode: ingress
        target: 5432
        published: "5434"
        protocol: tcp
    volumes:
      - type: volume
        source: postgres_subscription_data
        target: /var/lib/postgresql/data
        volume: {}
  redis:
    container_name: redis
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      timeout: 5s
      interval: 10s
      retries: 5
    image: redis:7-alpine
    networks:
      billing-network: null
    ports:
      - mode: ingress
        target: 6379
        published: "6379"
        protocol: tcp
  subscription-service:
    build:
      context: D:\Documents\Stages\Billing Saas App\saas-billing-platform\microservices\subscription-service
      dockerfile: Dockerfile
    container_name: subscription-service
    depends_on:
      kafka:
        condition: service_healthy
        required: true
      postgres-subscription:
        condition: service_healthy
        required: true
    environment:
      JWT_SECRET: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      PAYMENT_SERVICE_URL: http://payment-service:8084
      SPRING_DATASOURCE_PASSWORD: secret
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-subscription:5432/subscription_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "false"
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    networks:
      billing-network: null
    ports:
      - mode: ingress
        target: 8082
        published: "8082"
        protocol: tcp
    restart: on-failure
networks:
  billing-network:
    name: billing-network
    driver: bridge
volumes:
  postgres_auth_data:
    name: saas-billing-platform_postgres_auth_data
  postgres_billing_data:
    name: saas-billing-platform_postgres_billing_data
  postgres_dunning_data:
    name: saas-billing-platform_postgres_dunning_data
  postgres_notification_data:
    name: saas-billing-platform_postgres_notification_data
  postgres_payment_data:
    name: saas-billing-platform_postgres_payment_data
  postgres_subscription_data:
    name: saas-billing-platform_postgres_subscription_data
