spring:
  application:
    name: notification-service

  kafka:
    bootstrap-servers: kafka:29092
    consumer:
      group-id: notification-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false

  mail:
    host: mailhog
    port: 1025
    username: ""
    password: ""
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

server:
  port: 8086

app:
  mail:
    from: noreply@billflow.com